### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid reference index -1

### ISSUE THREAD

**Issue by thesnakeguy** [seppinho/mutserve#43]
Dear seppinho,

I am having trouble using mutserve call with whole mitogenome data.  I get  the following error when running the program:

```
File.bam[>-------------------------------------][00:00:00]
 null[>-------------------------------------][00:00:00]
java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
        at genepi.mut.tasks.VariantCallingTask.run(VariantCallingTask.java:129)
        at lukfor.progress.tasks.Task.call(Task.java:39)
        at lukfor.progress.tasks.Task.call(Task.java:8)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.Exception: Invalid reference index -1
Variant Calling failed. Mutserve terminated.

```
This is my workflow:
```
samtools faidx $GENOME
bwa mem -t $THREADS -R $RG $GENOME $fq1 $fq2 > $sam
samtools view -@ $THREADS -b $sam > $bam     
samtools sort -@ $THREADS $bam > $sorted_bam 
samtools index $sorted_bam
$MUT/mutserve call $sorted_bam --baseQ 25 --level 0.05 --output $variants --write-fasta true --threads $THREADS --reference=$GENOME
```

What am I doing wrong here? Many thanks!

Kind regards

**Comment by thesnakeguy** [comment]
Solved! The refence title contained spaces
